# Site settings
title: Kamil Janeczek
email: janeczekkamil@gmail.com
url: https://kamiljaneczek.github,io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Low code enthusiast, automation fan, digital transformation consultant, Pega developer"
meta_author: Kamil Janeczek

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6096BA
  primary-rgb: "0,288,16" #"128,179,255"
  secondary: 274C77 #FD6E8A
  secondary-dark: 19314D #A2122F red

# Footer settings
footer:
  copyright: Kamil Janeczek
  location: Good cause
  social: Social media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Pega
    url: https://academy.pega.com/verify-certification?email=kamil.janeczek%40pega.com
  - title: linkedin
    url: https://www.linkedin.com/in/kamil-janeczek/
  - title: github
    url: https://kamiljaneczek.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
