# Site settings
title: Kamil Janeczek
email: janeczekkamil@gmail.com
url: https://kamiljaneczek.github,io
description: "Kamil Janeczek. Low code enthusiast, automation supported, digital transformation consultant and Pega developer with LSA certification"
keywords: "Kamil Janeczek, Pega, LSA, Low code"
skills: "Low code enthusiast, automation advocate, open-source supported, digital transformation consultant, Pega developer with LSA certification"
meta_author: Kamil Janeczek

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 279185
  primary-rgb: "220,220,220" #"128,179,255"
  secondary: 344B47 #FD6E8A
  secondary-dark: 96B1AC #A2122F red

# Footer settings
footer:
  copyright: Kamil Janeczek
  location: Certification
  social: Social media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kamil-janeczek/
  - title: github
    url: https://kamiljaneczek.github.io
  - title: product-hunt
    url: https://academy.pega.com/verify-certification?email=kamil.janeczek%40pega.com    

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>. Avatar created thanks to <a href="https://avatarmaker.com/"> Avatarmaker</a>. Icons downloaded from <a href="https://www.flaticon.com/free-icons/quality" title="quality icons">Quality icons created by juicy_fish - Flaticon</a>.' 

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
